// This file is auto-generated by `src/utils/buildThemes.mjs`. Do not edit manually.
    export type ThemeNames =
      | "theme-light"
  | "theme-dark"
  | "theme-choco-mint"
  | "theme-deep-sea"
  | "theme-invisible"
  | "theme-leet"
  | "theme-neon-bliss"
  | "theme-old-couch"
  | "theme-peppermint"
  | "theme-pop-punk"
  | "theme-refresher"
  | "theme-slime"
  | "theme-syntax"
  | "theme-vanilla"
  | "theme-ocean-breeze"
  | "theme-sunset-groove"
  | "theme-forest-whisper"
  | "theme-cyberpunk-neon"
  | "theme-strawberry-cream";
    