plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
title: "Cmdlets and Coffee"
description: "Your daily brew for professional automation.""
author:
  name: "Tommy Becker"
  email: "mockmyberet@me.com"
url: "https://cmdletsandcoffee.github.io"
